// Dev-only: builds js/ui/fontdata.js
//  - Large font: rasterised from GNU Unifont (SIL OFL 1.1 / GPLv2+ w/ font exception)
//    via Chromium at exactly 16px so every outline pixel maps to one LCD dot.
//  - Small font: hand drawn in tools/font-small.txt
// Usage: node tools/build-font.mjs
import fs from 'node:fs';
import { createRequire } from 'node:module';
import { execSync } from 'node:child_process';

const require = createRequire(import.meta.url);
const pwPath = (() => { try { return require.resolve('playwright'); } catch { return require.resolve('playwright', { paths: [execSync('npm root -g').toString().trim()] }); } })();
const { chromium } = require(pwPath);

const LARGE_CHARS = [
  ...Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)),
  ...'×÷−±·•→←↑↓▶◀▲▼▷◁∠°′″πθσμλΣ∫√≈≠≤≥∞εαγΦτħℏΩδ⌟∣■□⇔▫',
  ...['𝑥', '𝑦', '𝑖', '𝑒', '𝑎', '𝑏', '𝑐', '𝑟', '𝑛', '𝑡', '𝑝'],
];

function parseHandFont(file, rowsTotal, topPad) {
  const txt = fs.readFileSync(file, 'utf8').split('\n');
  const glyphs = {};
  let cur = null;
  for (const line of txt) {
    if (line.startsWith('#') && !cur) continue;
    if (line.startsWith('@ ')) {
      cur = { ch: line.slice(2), rows: [] };
      glyphs[cur.ch] = cur;
      continue;
    }
    if (cur && /^[.#]+$/.test(line)) cur.rows.push(line);
  }
  const out = {};
  for (const [ch, g] of Object.entries(glyphs)) {
    const w = g.rows[0].length;
    const rows = [];
    for (let i = 0; i < topPad; i++) rows.push('.'.repeat(w));
    rows.push(...g.rows);
    while (rows.length < rowsTotal) rows.push('.'.repeat(w));
    out[ch] = rows;
  }
  return out;
}

function encode(rows) {
  const w = rows[0].length;
  const bits = rows.map((r) => {
    let v = 0;
    for (let i = 0; i < w; i++) if (r[i] === '#') v |= 1 << (w - 1 - i);
    return v.toString(36);
  });
  return [w, bits.join(',')];
}

const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' }).catch(() => chromium.launch());
const page = await browser.newPage();
const raw = await page.evaluate((chars) => {
  const c = document.createElement('canvas');
  c.width = 48; c.height = 32;
  const g = c.getContext('2d', { willReadFrequently: true });
  const res = {};
  for (const ch of chars) {
    g.clearRect(0, 0, 48, 32);
    g.font = '16px Unifont, "Unifont Upper"';
    g.fillStyle = '#000';
    g.textBaseline = 'alphabetic';
    const cp = ch.codePointAt(0);
    if (cp > 0xffff) g.font = '16px "Unifont Upper", Unifont';
    g.fillText(ch, 8, 8 + 14);
    const d = g.getImageData(0, 0, 48, 32).data;
    const rows = [];
    let minx = 99, maxx = -1;
    for (let y = 8 + 2; y < 8 + 16; y++) {
      let r = '';
      for (let x = 0; x < 48; x++) {
        const on = d[(y * 48 + x) * 4 + 3] > 127;
        r += on ? '#' : '.';
        if (on) { minx = Math.min(minx, x); maxx = Math.max(maxx, x); }
      }
      rows.push(r);
    }
    const adv = Math.round(g.measureText(ch).width);
    res[ch] = maxx < 0 ? { empty: true, adv } : { rows: rows.map((r) => r.slice(minx, maxx + 1)) };
  }
  return res;
}, LARGE_CHARS);
await browser.close();

const large = {};
for (const [ch, g] of Object.entries(raw)) {
  if (g.empty) large[ch] = Array.from({ length: 14 }, () => '.'.repeat(ch === ' ' ? 4 : Math.max(1, g.adv - 2)));
  else large[ch] = g.rows;
}
// hand overrides for the large font (same format as the small font, 14 rows)
if (fs.existsSync('tools/font-large-overrides.txt')) {
  Object.assign(large, parseHandFont('tools/font-large-overrides.txt', 14, 0));
}
const small = parseHandFont('tools/font-small.txt', 10, 1);

const enc = (f) => Object.fromEntries(Object.entries(f).map(([k, v]) => [k, encode(v)]));
const out = `// Generated by tools/build-font.mjs - do not edit by hand.
// Large font glyphs derived from GNU Unifont (SIL Open Font License 1.1).
// Small font hand drawn for this project.
// Each glyph: [width, "row,row,..."] rows are base-36 bitmasks, MSB = leftmost pixel.
export const LARGE = { h: 14, base: 11, glyphs: ${JSON.stringify(enc(large))} };
export const SMALL = { h: 10, base: 7, glyphs: ${JSON.stringify(enc(small))} };
`;
fs.writeFileSync('js/ui/fontdata.js', out);
console.log('large', Object.keys(large).length, 'small', Object.keys(small).length, 'bytes', out.length);
