// Dev-only: builds js/ui/fontdata.js from the hand-drawn LCD fonts
//  - Large font: tools/font-large.txt (9x14 character cells, 14 rows per glyph)
//  - Small font: tools/font-small.txt (rows 1..7 cap height + 2 descender rows)
// Usage: node tools/build-font.mjs
import fs from 'node:fs';

function parseHandFont(file, rowsTotal, topPad) {
  const txt = fs.readFileSync(file, 'utf8').split('\n');
  const glyphs = {};
  let cur = null;
  for (const line of txt) {
    if (line.startsWith('#') && !cur) continue;
    if (line.startsWith('@ ')) {
      cur = { ch: line.slice(2), rows: [] };
      glyphs[cur.ch] = cur;
      continue;
    }
    if (cur && /^[.#]+$/.test(line)) cur.rows.push(line);
  }
  const out = {};
  for (const [ch, g] of Object.entries(glyphs)) {
    const w = g.rows[0].length;
    if (g.rows.some((r) => r.length !== w)) throw new Error(`${file}: rows of "${ch}" differ in width`);
    const rows = [];
    for (let i = 0; i < topPad; i++) rows.push('.'.repeat(w));
    rows.push(...g.rows);
    if (rows.length > rowsTotal) throw new Error(`${file}: "${ch}" has more than ${rowsTotal} rows`);
    while (rows.length < rowsTotal) rows.push('.'.repeat(w));
    out[ch] = rows;
  }
  return out;
}

function encode(rows) {
  const w = rows[0].length;
  const bits = rows.map((r) => {
    let v = 0;
    for (let i = 0; i < w; i++) if (r[i] === '#') v |= 1 << (w - 1 - i);
    return v.toString(36);
  });
  return [w, bits.join(',')];
}

const large = parseHandFont('tools/font-large.txt', 14, 0);
const small = parseHandFont('tools/font-small.txt', 10, 1);

const enc = (f) => Object.fromEntries(Object.entries(f).map(([k, v]) => [k, encode(v)]));
const out = `// Generated by tools/build-font.mjs - do not edit by hand.
// Both fonts hand drawn for this project (tools/font-large.txt, tools/font-small.txt).
// Each glyph: [width, "row,row,..."] rows are base-36 bitmasks, MSB = leftmost pixel.
export const LARGE = { h: 14, base: 11, glyphs: ${JSON.stringify(enc(large))} };
export const SMALL = { h: 10, base: 7, glyphs: ${JSON.stringify(enc(small))} };
`;
fs.writeFileSync('js/ui/fontdata.js', out);
console.log('large', Object.keys(large).length, 'small', Object.keys(small).length, 'bytes', out.length);
